= Docker environment for the data science training

Make sure you install Docker and https://docs.docker.com/compose/install/[Docker Compose^] before following the instructions below.

== Launch the environment

=== On all environment

Clone this repository, by running the following command:

[source,bash]
----
git clone https://github.com/mneedham/docker-data-science-training.git
----

==== Step 1 : Clone the training repository

In this directory, clone the training repository : `git clone https://github.com/mneedham/gds-data-science-training data-science-training`

==== Step 2 : Launch docker

Now run `docker-compose up`

== Use the environment

Your Neo4j database is available on your laptop at this url http://localhost:7474/browser with the following login/password -> neo4j / admin
But inside other container (like the jupyter one) your should use `bolt://data-science-training-neo4j`.

Jupyter is available at the following url http://localhost:8888/
To login, you will need to search the token in the docker logs something. You should see something similar to:

[source,text]
----
[I 17:39:57.299 NotebookApp] http://(9d6f11a3c1a1 or 127.0.0.1):8888/?token=04833158d59cd1ac094602f9b097822a904fa285607e1c59
----
